"""
Scaffold templates for `shreyzen init`.

Templates are plain strings with ``{{TOKEN}}`` sentinels (double braces, so they
never collide with the single braces in Python code / dicts). Render with
:func:`render`, which does a straight token substitution — no template engine,
no autoescaping surprises.

Tokens:
  {{APP_NAME}}    human-readable project name (e.g. "Acme Store")
  {{BASE_URL}}    application root URL (e.g. https://acme.example.com)
  {{PAGE_CLASS}}  Page Object class name (e.g. HomePage)
  {{PAGE_SLUG}}   snake_case page name (e.g. home)
  {{START_PATH}}  path relative to BASE_URL the page navigates to (e.g. /)
"""

from __future__ import annotations


def render(template: str, **tokens: str) -> str:
    """Substitute ``{{TOKEN}}`` placeholders in *template* with *tokens*."""
    out = template
    for key, value in tokens.items():
        out = out.replace("{{" + key + "}}", value)
    return out


# ── Page Object ──────────────────────────────────────────────────────────────

PAGE_OBJECT = '''"""
{{PAGE_CLASS}} — Page Object for {{APP_NAME}}.

Locators live in @property methods; actions call BasePage helpers.
Never put assertions here — those belong in the test.

Generated by `shreyzen init`. Replace the placeholder locators below with your
app's real selectors. Prefer role / label / test-id locators over brittle CSS.
"""

from playwright.sync_api import Locator
from pages.base_page import BasePage


class {{PAGE_CLASS}}(BasePage):
    URL = "{{START_PATH}}"

    # ── Locators ──────────────────────────────────────────────────────────────

    @property
    def heading(self) -> Locator:
        # TODO: point this at your page's main heading.
        return self.page.get_by_role("heading").first

    # ── Navigation ────────────────────────────────────────────────────────────

    def navigate(self) -> None:
        self.goto(self.URL)
'''


# ── Web smoke test ─────────────────────────────────────────────────────────

WEB_TEST = '''"""
Smoke test for {{APP_NAME}} — generated by `shreyzen init`.

Instantiates the Page Object directly (no shared fixture needed). Replace the
placeholder assertion with a real check once you've filled in the locators.
"""

import pytest
from playwright.sync_api import Page, expect

from pages.{{PAGE_SLUG}}_page import {{PAGE_CLASS}}

pytestmark = pytest.mark.web


@pytest.mark.smoke
def test_{{PAGE_SLUG}}_page_loads(page: Page):
    """The {{PAGE_SLUG}} page loads and renders its primary content."""
    {{PAGE_SLUG}} = {{PAGE_CLASS}}(page)
    {{PAGE_SLUG}}.navigate()

    # TODO: replace with a real assertion for your app.
    expect({{PAGE_SLUG}}.heading).to_be_visible()
'''


# ── Mobile smoke test ──────────────────────────────────────────────────────

MOBILE_TEST = '''"""
Mobile smoke test for {{APP_NAME}} — generated by `shreyzen init`.

Runs under mobile-device emulation (see tests/mobile/conftest.py). Pick a device
with:  MOBILE_DEVICE="iPhone 13" pytest tests/mobile -v
"""

import pytest
from playwright.sync_api import Page, expect

from pages.{{PAGE_SLUG}}_page import {{PAGE_CLASS}}

pytestmark = pytest.mark.mobile


@pytest.mark.smoke
def test_{{PAGE_SLUG}}_loads_on_mobile(page: Page):
    """The {{PAGE_SLUG}} page renders under a mobile viewport."""
    {{PAGE_SLUG}} = {{PAGE_CLASS}}(page)
    {{PAGE_SLUG}}.navigate()

    # TODO: replace with a real assertion for your app.
    expect({{PAGE_SLUG}}.heading).to_be_visible()
'''


# ── API contract smoke test ────────────────────────────────────────────────

API_TEST = '''"""
API contract smoke test for {{APP_NAME}} — generated by `shreyzen init`.

Validates the shape of a response with a Pydantic model (Pydantic raises on a
schema mismatch). Point BASE_URL / the endpoint at your own API.
"""

import pytest
import requests
from pydantic import BaseModel

pytestmark = pytest.mark.api

API_BASE_URL = "{{BASE_URL}}"


class HealthResponse(BaseModel):
    # TODO: describe the real response shape for your endpoint.
    status: str


@pytest.mark.smoke
def test_health_endpoint_contract():
    """The health endpoint responds 200 and matches its contract."""
    resp = requests.get(f"{API_BASE_URL}/health", timeout=10)
    assert resp.status_code == 200, f"expected 200, got {resp.status_code}"
    HealthResponse.model_validate(resp.json())  # raises ValidationError on drift
'''


# Map a template name to (page_object?, test_body, test_subdir).
TEMPLATES = {
    "web":    {"page": True,  "test": WEB_TEST,    "subdir": "web"},
    "mobile": {"page": True,  "test": MOBILE_TEST, "subdir": "mobile"},
    "api":    {"page": False, "test": API_TEST,    "subdir": "api"},
}
